apiVersion: apps/v1
kind: Deployment
metadata:
  name: libvirt-nodemanager
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: libvirt-nodemanager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: libvirt-nodemanager
      annotations:
        autocert.step.sm/name: libvirt-nodemanager.autoscaler.svc.cluster.local
    spec:
      serviceAccountName: nodemanager
      automountServiceAccountToken: true
      containers:
      - image: SET-IN-KUSTOMIZE/libvirt_nodemanager
        imagePullPolicy: Always
        name: libvirt-nodemanager
        env:
        ports:
        - containerPort: 50051
          protocol: TCP
        resources:
          requests:
            cpu: 512m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 10000
        runAsUser: 10000
      terminationGracePeriodSeconds: 30
